### ISSUE TITLE
Error: the thunkFunction already filled at child

### ISSUE THREAD

**Issue by danvernon** [holger1411/understrap-child#65]
`[BS] Watching files...
[BS] Reloading Browsers...
[14:06:19] Starting 'styles'...
[14:06:19] Starting 'sass'...
[14:06:19] Finished 'sass' after 609 ms
[14:06:19] Starting 'minify-css'...
[14:06:20] Finished 'minify-css' after 465 ms
[14:06:20] Finished 'styles' after 1.08 s
[BS] File event [change] : css/child-theme.min.css
[14:23:03] Starting 'styles'...
[14:23:03] 'styles' errored after 239 μs
[14:23:03] Error: The thunkFunction already filled
    at child (/Users/Laptop/Documents/Sites/unilad/wp-content/themes/wildfire/node_modules/gulp-sequence/node_modules/thunks/thunks.js:150:32)
    at Gulp.thunkFunction (/Users/Laptop/Documents/Sites/unilad/wp-content/themes/wildfire/node_modules/gulp-sequence/node_modules/thunks/thunks.js:145:14)
    at module.exports (/Users/Laptop/Documents/Sites/unilad/wp-content/themes/wildfire/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/Laptop/Documents/Sites/unilad/wp-content/themes/wildfire/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/Laptop/Documents/Sites/unilad/wp-content/themes/wildfire/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/Laptop/Documents/Sites/unilad/wp-content/themes/wildfire/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at Gulp.<anonymous> (/Users/Laptop/Documents/Sites/unilad/wp-content/themes/wildfire/node_modules/gulp/index.js:36:18)
    at Gaze.<anonymous> (/Users/Laptop/Documents/Sites/unilad/wp-content/themes/wildfire/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:18:14)
    at emitTwo (events.js:87:13)
    at Gaze.emit (events.js:172:7)`

**Comment by jGoose** [comment]
I was able to fix this error by adding a callback function to the styles task in gulpfile.js.

Here is the original code on line 158:
`gulp.task('styles', gulpSequence('sass', 'minify-css'))`

This is the modification that fixed my error:
`gulp.task('styles', function(callback){
	gulpSequence('sass', 'minify-css')(callback)
});`

I found this solution in [this comment](https://github.com/teambition/gulp-sequence/issues/2#issuecomment-78720934).

**Comment by danvernon** [comment]
@jGoose thanks!

**Comment by hotrush** [comment]
confirmed, it works

**Comment by holger1411** [comment]
Confirmed. Add it to the next release.
